#zf210525.0147
#source: https://github.com/ccrisan/motioneye/blob/dev/extra/docker-compose.yml

version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - $PWD/etc_motioneye:/etc/motioneye
      - $PWD/var_lib_motioneye:/var/lib/motioneye
      - /etc/localtime:/etc/localtime:ro

# volumes:
#   etc_motioneye:
#   var_lib_motioneye:


